### ISSUE TITLE
Feedstock outdated

### ISSUE THREAD

**Issue by tdegeus** [conda-forge/catch2-feedstock#32]
The latest version of Catch2 is v.2.13.1, but the feedstock is only at v.2.11.3. Can this be upgraded ?

**Comment by mjscosta** [comment]
Hi @tdegeus, I'm working on updating the feedstock thanks for your feedback.

**Comment by mjscosta** [comment]
The error seems to be related to the gcc version,

In the ppc environment the gcc version is 8.4
https://api.travis-ci.org/v3/job/726135670/log.txt

In the linux version the gcc version is 7.5
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/207695/logs/17

According to https://en.cppreference.com/w/cpp/error/uncaught_exception, is deprecated in c++17, and gcc 8.4 already implemented the deprecation warning.

Since testes are running with option 
// Enable all warnings as errors
CATCH_ENABLE_WERROR:BOOL=ON
This results in failed tests when using gcc 8.4

**Comment by mjscosta** [comment]
Possible solution disable cmake option CATCH_ENABLE_WERROR.

**Comment by tdegeus** [comment]
Thanks for the fix!
